[package]
name = "tether-lidar2d-consolidation-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.11.1"
env_logger = "0.7"
futures = "0.3"
async-std = "1"
petal-clustering = "0.5.1"
petal-neighbors = "0.8.0"
ndarray = "0.15.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
rmp-serde = "1.1.1"

[dev-dependencies]