[package]
name = "tether-lidar2d-consolidation-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.11.1"
env_logger = "0.7"
futures = "0.3"
async-std = "1"

[dev-dependencies]