[package]
name = "lidar2d-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tether-lidar2d-consolidation = { path = "../backend"}